[tox]
envlist = py{38,39,310,311,312},docs

[testenv]
passenv = test_flags
commands =
    coverage run --source=katportalclient -m pytest {env:test_flags:katportalclient/test}
    coverage xml -o coverage_{envname}.xml
    coverage html
    coverage report -m --skip-covered
deps =
    coverage
    mock
    pytest
    pytest-asyncio

[testenv:docs]
# Python interpreter which will be used for creating the virtual environment.
basepython = python3.8
# whitelisting non-virtualenv commands.
whitelist_externals = make
changedir = docs
commands = make html
deps =
    sphinx>=1.2.3, <2.0
    docutils>=0.12, <1.0
    sphinx_rtd_theme>=0.1.5, <1.0
    numpydoc>=0.5, <1.0
